// build.js — Vercel deploy pe config.js generate karta hai
// Sirf EmailJS keys inject karta hai — Firebase keys nahi!
const fs = require('fs');

const config = `// AUTO-GENERATED by build.js — DO NOT EDIT
window.EMAILJS_PUBLIC_KEY  = "${process.env.EMAILJS_PUBLIC_KEY  || ''}";
window.EMAILJS_SERVICE_ID  = "${process.env.EMAILJS_SERVICE_ID  || ''}";
window.EMAILJS_TEMPLATE_ID = "${process.env.EMAILJS_TEMPLATE_ID || ''}";
`;

fs.writeFileSync('config.js', config);
console.log('✅ config.js generated — Firebase keys NOT exposed');